apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-config
  namespace: 5g-lab
data:
  gnb.yaml: |
    mcc: '001'
    mnc: '01'
    nci: '0x00000001'
    idLength: 32
    tac: 1
    linkIp: 127.0.0.1
    ngapIp: 127.0.0.1
    gtpuIp: 127.0.0.1
    amfConfigs:
      - address: my-5g-core-amf
        port: 38412
    slices:
      - sst: 1
        sd: 0x010203
    gnbId: '0x000102'
